name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Build project
        run: |
          make all

      - name: Generate Changelog
        run: |
          VERSION=${{ env.LATEST_TAG }}
          hack/changelog.sh $VERSION > build/CHANGELOG.md
          echo "VERSION=$VERSION"
          ls -R build
          cat build/CHANGELOG.md
          ls -lath .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.LATEST_TAG }}
          body_path: build/CHANGELOG.md
          files: build/ansiblesafe-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
